CERT ENV
###
GET http://localhost:3000/menu

###


GET http://localhost:3000/menu/63c8e2c874257b54b01d86c5



###

GET http://localhost:3000/


###

POST http://localhost:3000/menu HTTP/1.1
content-type: application/json

{
"foodName":"Lasagna", 
"preparationTime":"50min",
 "ingredients":["Cheese", "Dough", "Meat"], 
 "chefName":"Agustin",
 "idInTheMenu":"1", 
 "restaurantName":"Nico's",
 "score":"4"
}

###

PROD ENV
###
GET https://crazy341myownproject.onrender.com/3000/menu

###


GET https://crazy341myownproject.onrender.com/menu/63c8e2c874257b54b01d86c5



###

GET https://crazy341myownproject.onrender.com/


###

POST https://crazy341myownproject.onrender.com/menu HTTP/1.1
content-type: application/json

{
"foodName":"NewForTesting", 
"preparationTime":"50min",
 "ingredients":["Cheese", "Dough", "Meat"], 
 "chefName":"Agustin",
 "idInTheMenu":"1", 
 "restaurantName":"Nico's",
 "score":"4"
}
